//! The foreman record: an append-only trajectory of a participant's declared and observed
//! activity, and the coherence check over it.
//!
//! From `notes/16-foreman-as-continuous-verification.md`. The foreman is the app a farmer
//! uses to run their season; its record happens also to be the audit trail. That is the
//! whole trick — the verification layer is a by-product of something the participant wants
//! anyway, so it accumulates before any trade rather than after a dispute.
//!
//! # What this module is not
//!
//! It is not an AI assistant. The assistant is a thing that *reads* this record and talks
//! to a human; it lives outside the core and may write nothing here except through
//! [`crate::proposal`]. The record itself, and the coherence check over it, are
//! deterministic — an alert must be recomputable from the ledger years later, by someone
//! who does not have the model that raised it.
//!
//! # ⭐ Why every step carries a `Source`
//!
//! A [`Step`] generated by the system is not evidence about the physical world. It is
//! evidence about what was *entered*. If monitoring silently promoted system-generated
//! records to observed status, the exchange would be a machine that confirms its own
//! inputs — a fabricated season would validate itself simply by being typed in.
//!
//! So `Step::source` is mandatory and the coherence check reports the
//! [`Confidence`] of the loop it closed. An alert on a wholly-asserted cycle means
//! "these claims disagree with each other", which is worth knowing. It does not mean
//! "reality disagrees with the claim", and the two must not be reported as the same thing.
//!
//! # Decoder-disjointness
//!
//! Note 16 §2.1: floors multiply only across sources that share no representation
//! alphabet. A farmer's SMS, a satellite raster and a weighbridge ticket are disjoint;
//! three SMSes from the same farmer are not. [`Cycle::disjoint_source_count`] counts
//! distinct sources rather than steps, so re-inspecting the same way twice earns nothing.

use crate::provenance::{Confidence, Field, Source};
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;

/// What a participant did, or what was observed of them.
///
/// Deliberately a small closed set. An open-ended "activity" string would let the record
/// accumulate categories nobody can write a coherence check against, and an unverifiable
/// record is the thing this module exists to avoid.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Activity {
    Planted,
    InputPurchase,
    Sprayed,
    Irrigated,
    GreenUp,
    Harvested,
    Stored,
    Dispatched,
    Delivered,
}

/// How a step resolved.
///
/// From the `.smith` DSL's `StepRecord`. ⭐ `Observe` is distinct from `Decline`, and the
/// distinction is load-bearing: a participant who saw an offer and is *gathering
/// information* sits in the missing-information region of
/// `notes/27-miracles-are-for-missing-information.md`, which is a different state from one
/// who evaluated and refused. An accept/reject model loses exactly that.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Outcome {
    Commit,
    Observe,
    Decline,
    Quiescent,
}

/// Which phase of a coalition a step belongs to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Phase {
    Construction,
    Commitment,
}

/// One committed entry in the record.
///
/// ⚠️ Steps are never mutated. A correction is a new step that supersedes an earlier one
/// by index; both remain in the record. That is what makes fabrication accumulate rather
/// than being quietly revised (note 16 §2.3).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Step {
    /// Monotone sequence number within the record. Assigned by [`Record::append`], not by
    /// the caller — a client-chosen tick could be used to reorder history.
    pub tick: u64,
    pub activity: Activity,
    pub outcome: Outcome,
    pub phase: Phase,
    /// ⭐ Where this step came from. Never inferred, never upgraded after the fact.
    pub source: Source,
    /// The quantity this step reports, if it reports one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Field>,
    /// Free-text note from the participant. Carried, never parsed — anything a coherence
    /// check depends on must be a typed field.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// Index of the step this one corrects, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supersedes: Option<u64>,
}

impl Step {
    /// A step the participant declared themselves.
    pub fn declared(activity: Activity, outcome: Outcome, phase: Phase) -> Self {
        Step {
            tick: 0,
            activity,
            outcome,
            phase,
            source: Source::Asserted,
            quantity: None,
            note: None,
            supersedes: None,
        }
    }

    /// A step backed by something other than the participant's word.
    pub fn observed(activity: Activity, outcome: Outcome, phase: Phase, source: Source) -> Self {
        Step {
            source,
            ..Step::declared(activity, outcome, phase)
        }
    }

    pub fn with_quantity(mut self, field: Field) -> Self {
        self.quantity = Some(field);
        self
    }

    pub fn with_note(mut self, note: impl Into<String>) -> Self {
        self.note = Some(note.into());
        self
    }

    /// Mark this step as correcting an earlier one.
    pub fn correcting(mut self, tick: u64) -> Self {
        self.supersedes = Some(tick);
        self
    }
}

/// Why an append was refused.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum RecordError {
    /// A correction referenced a tick that does not exist. Silently accepting it would
    /// leave a dangling supersession in an append-only log.
    #[error("step supersedes tick {tick}, which is not in the record")]
    DanglingSupersession { tick: u64 },
    /// A step cannot supersede itself or a later step.
    #[error("step at tick {tick} cannot supersede tick {target} (not strictly earlier)")]
    NonMonotoneSupersession { tick: u64, target: u64 },
}

/// An append-only record for one participant.
///
/// There is no `remove`, no `get_mut`, and no way to reorder. The only mutation is
/// [`Record::append`], which assigns the next tick.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Record {
    steps: Vec<Step>,
}

impl Record {
    pub fn new() -> Self {
        Record::default()
    }

    /// Append a step, assigning it the next tick. Returns the assigned tick.
    pub fn append(&mut self, mut step: Step) -> Result<u64, RecordError> {
        let tick = self.steps.len() as u64;
        if let Some(target) = step.supersedes {
            // A step may only supersede one strictly earlier than itself. Since ticks are
            // dense from 0, `target < tick` is simultaneously the existence check and the
            // monotonicity check — the two failures are distinguished only for the
            // message, and `target == tick` (superseding the slot this step is about to
            // occupy) is the non-monotone case, not the dangling one.
            if target >= tick {
                return Err(if target == tick {
                    RecordError::NonMonotoneSupersession { tick, target }
                } else {
                    RecordError::DanglingSupersession { tick: target }
                });
            }
        }
        step.tick = tick;
        self.steps.push(step);
        Ok(tick)
    }

    pub fn steps(&self) -> &[Step] {
        &self.steps
    }

    pub fn len(&self) -> usize {
        self.steps.len()
    }

    pub fn is_empty(&self) -> bool {
        self.steps.is_empty()
    }

    /// Ticks that have been superseded by a later correction.
    pub fn superseded(&self) -> BTreeSet<u64> {
        self.steps.iter().filter_map(|s| s.supersedes).collect()
    }

    /// The steps that stand — corrections applied, originals retained in the log but not
    /// returned here.
    ///
    /// ⭐ The originals are *not* deleted. `steps()` still shows them, which is what makes
    /// a pattern of revisions visible to an auditor.
    pub fn current(&self) -> Vec<&Step> {
        let superseded = self.superseded();
        self.steps
            .iter()
            .filter(|s| !superseded.contains(&s.tick))
            .collect()
    }

    /// The most recent standing step for an activity, if any.
    pub fn latest(&self, activity: Activity) -> Option<&Step> {
        self.current()
            .into_iter()
            .rev()
            .find(|s| s.activity == activity)
    }

    /// How many times an activity has been revised. A high count on a quantity-bearing
    /// activity is worth a human look.
    pub fn revision_count(&self, activity: Activity) -> usize {
        let superseded = self.superseded();
        self.steps
            .iter()
            .filter(|s| s.activity == activity && superseded.contains(&s.tick))
            .count()
    }
}

// ---------------------------------------------------------------------------------------
// Cycle coherence
// ---------------------------------------------------------------------------------------

/// One leg of a coherence cycle: a quantity that should reconcile with the others.
///
/// A cycle is a loop of implications — declared area × declared yield/ha should equal
/// declared harvest; declared inputs should imply the same area; satellite green-up should
/// imply the same planting date. Going round the loop, the discrepancy should return to
/// zero (note 16 §2.2).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Leg {
    pub name: String,
    /// The value this leg implies for the cycle's common quantity, in the cycle's unit.
    pub implied: Field,
}

impl Leg {
    pub fn new(name: impl Into<String>, implied: Field) -> Self {
        Leg {
            name: name.into(),
            implied,
        }
    }
}

/// A closed loop of implications about the same quantity, arrived at different ways.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Cycle {
    pub name: String,
    pub legs: Vec<Leg>,
}

impl Cycle {
    pub fn new(name: impl Into<String>, legs: Vec<Leg>) -> Self {
        Cycle {
            name: name.into(),
            legs,
        }
    }

    /// Number of *distinct* sources across the legs.
    ///
    /// ⭐ Distinct, not total. Three declarations from the same farmer are one source
    /// (note 16 §2.1, the anti-monoculture result): floors multiply only across
    /// decoder-disjoint sources, so re-inspecting the same way twice adds nothing.
    pub fn disjoint_source_count(&self) -> usize {
        self.legs
            .iter()
            .map(|l| l.implied.source)
            .collect::<BTreeSet<_>>()
            .len()
    }

    /// Confidence over the legs — the floor, and which legs are unbacked.
    pub fn confidence(&self) -> Confidence {
        Confidence::over(self.legs.iter().map(|l| (l.name.as_str(), &l.implied)))
    }
}

/// How a coherence check resolved.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Closure {
    /// The loop closes within the measurement floor. Nothing to say.
    Coherent,
    /// The loop does not close, and the discrepancy exceeds β. A real inconsistency.
    Incoherent,
    /// The discrepancy exceeds β but the legs are not decoder-disjoint — fewer than two
    /// distinct sources. ⚠️ This is *contested*, not *incoherent*: the claims disagree
    /// with each other, which is not the same as reality disagreeing with a claim.
    Contested,
    /// The discrepancy is below β. ⭐ **Not "coherent" — unresolvable.** Below the floor,
    /// fraud and measurement noise are provably indistinguishable
    /// (`notes/12-irreducible-bounded-phase-space.md`), and adjudicating here is
    /// attempting the impossible. The honest output is that the question cannot be
    /// answered, not that the answer is "fine".
    SubFloor,
    /// Fewer than two legs. Nothing to close.
    Degenerate,
}

impl Closure {
    /// True when a human should be shown this.
    ///
    /// `SubFloor` deliberately does not alert: β is the no-alert band, and alerting inside
    /// it trains everyone to ignore alerts.
    pub fn alerts(self) -> bool {
        matches!(self, Closure::Incoherent | Closure::Contested)
    }
}

/// The result of walking a cycle.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Coherence {
    pub cycle: String,
    pub closure: Closure,
    /// Spread across the legs: `max − min` of the implied values.
    pub discrepancy: f64,
    /// The accumulated measurement floor β around the loop — the band inside which the
    /// discrepancy carries no information.
    pub beta: f64,
    /// Distinct sources among the legs.
    pub disjoint_sources: usize,
    /// Confidence over the legs. Reported alongside the closure so a reader can tell an
    /// alert on weighbridge data from an alert on three guesses.
    pub confidence: Confidence,
    /// ⭐ The banded estimate: `[min, max]` over the legs, widened to at least β.
    ///
    /// Note 16 §2.4 — forward contracts must be written against a band, never a point.
    /// The residual never goes to zero; publishing a point estimate would be claiming it
    /// had.
    pub band: (f64, f64),
}

impl Coherence {
    /// Width of the published band. A narrowing band across the season is the product
    /// (note 16 §3.4).
    pub fn band_width(&self) -> f64 {
        self.band.1 - self.band.0
    }
}

/// The accumulated measurement floor around a cycle.
///
/// Each leg contributes its own tolerance to the quantity it implies; the loop's floor is
/// their sum, because the discrepancy accumulates the uncertainty of every step taken to
/// get round it.
///
/// ⚠️ A leg of unknown precision contributes [`UNKNOWN_PRECISION_BETA`] times its value
/// rather than zero. Treating unknown precision as *perfect* precision would make β
/// artificially tight and generate alerts that are pure noise — the opposite of the
/// intended failure direction.
fn accumulated_beta(cycle: &Cycle) -> f64 {
    cycle
        .legs
        .iter()
        .map(|leg| {
            let tolerance = leg.implied.precision.0.unwrap_or(UNKNOWN_PRECISION_BETA);
            leg.implied.value.abs() * tolerance
        })
        .sum()
}

/// Relative tolerance assumed for a leg whose precision is not stated.
///
/// ⚠️ **Authored, and not empirically justified.** It is part of `Φ_R` and must be
/// published with it. 20% is a placeholder chosen to be clearly wider than any stated
/// tolerance in the system, so that unknown precision is never accidentally the tightest
/// leg. It should be replaced by a measured value — the same open gap as the cohesion
/// test's `min_separation`.
pub const UNKNOWN_PRECISION_BETA: f64 = 0.20;

/// Walk a cycle and report whether it closes.
///
/// The alert threshold is *derived* — β, the accumulated floor — not chosen (note 16
/// §2.2). That is the difference between a threshold someone can be accused of tuning and
/// one that falls out of the measurements.
pub fn check_cycle(cycle: &Cycle) -> Coherence {
    let confidence = cycle.confidence();
    let disjoint_sources = cycle.disjoint_source_count();

    if cycle.legs.len() < 2 {
        let v = cycle.legs.first().map_or(0.0, |l| l.implied.value);
        return Coherence {
            cycle: cycle.name.clone(),
            closure: Closure::Degenerate,
            discrepancy: 0.0,
            beta: 0.0,
            disjoint_sources,
            confidence,
            band: (v, v),
        };
    }

    let values: Vec<f64> = cycle.legs.iter().map(|l| l.implied.value).collect();
    let min = values.iter().copied().fold(f64::INFINITY, f64::min);
    let max = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let discrepancy = max - min;
    let beta = accumulated_beta(cycle);

    let closure = if discrepancy <= beta {
        Closure::SubFloor
    } else if disjoint_sources < 2 {
        // The legs disagree, but they all came the same way. Note 16 §2.1: correlated
        // sources do not compose, so this cannot be called an inconsistency with reality.
        Closure::Contested
    } else {
        Closure::Incoherent
    };

    // The band is the spread, widened to at least β — never narrower than the floor,
    // because claiming precision below the measurement floor is the error note 16 §2.4
    // exists to prevent.
    let centre = (min + max) / 2.0;
    let half = ((max - min) / 2.0).max(beta / 2.0);

    Coherence {
        cycle: cycle.name.clone(),
        closure,
        discrepancy,
        beta,
        disjoint_sources,
        confidence,
        band: (centre - half, centre + half),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::provenance::Precision;
    use crate::units::Unit;

    fn t(value: f64, source: Source, tolerance: Option<f64>) -> Field {
        Field {
            value,
            unit: Unit::Tonnes,
            source,
            precision: tolerance.map_or(Precision::unknown(), Precision::relative),
        }
    }

    // --- the record ---

    #[test]
    fn ticks_are_assigned_by_the_record_not_the_caller() {
        let mut r = Record::new();
        let mut planted = Step::declared(Activity::Planted, Outcome::Commit, Phase::Construction);
        planted.tick = 999; // a client trying to choose its own position in history
        assert_eq!(r.append(planted).unwrap(), 0);
        assert_eq!(r.steps()[0].tick, 0);
    }

    #[test]
    fn a_correction_appends_beside_the_original_and_never_replaces_it() {
        let mut r = Record::new();
        r.append(
            Step::declared(Activity::Harvested, Outcome::Commit, Phase::Commitment)
                .with_quantity(t(20.0, Source::Asserted, None)),
        )
        .unwrap();
        r.append(
            Step::observed(
                Activity::Harvested,
                Outcome::Commit,
                Phase::Commitment,
                Source::Weighbridge,
            )
            .with_quantity(t(18.4, Source::Weighbridge, Some(0.02)))
            .correcting(0),
        )
        .unwrap();

        // Both are in the log — the original claim of 20t does not disappear.
        assert_eq!(r.len(), 2);
        assert_eq!(r.steps()[0].quantity.as_ref().unwrap().value, 20.0);
        // But only the correction stands.
        assert_eq!(r.current().len(), 1);
        assert_eq!(r.latest(Activity::Harvested).unwrap().tick, 1);
        assert_eq!(r.revision_count(Activity::Harvested), 1);
    }

    #[test]
    fn history_cannot_be_reordered_by_a_dangling_or_forward_supersession() {
        let mut r = Record::new();
        r.append(Step::declared(
            Activity::Planted,
            Outcome::Commit,
            Phase::Construction,
        ))
        .unwrap();

        let dangling =
            Step::declared(Activity::Planted, Outcome::Commit, Phase::Construction).correcting(57);
        assert!(matches!(
            r.append(dangling),
            Err(RecordError::DanglingSupersession { tick: 57 })
        ));

        // Superseding the tick this step is about to occupy is also refused.
        let selfref =
            Step::declared(Activity::Planted, Outcome::Commit, Phase::Construction).correcting(1);
        assert!(matches!(
            r.append(selfref),
            Err(RecordError::NonMonotoneSupersession { .. })
        ));
        assert_eq!(r.len(), 1, "refused appends leave the record untouched");
    }

    #[test]
    fn observe_is_carried_distinctly_from_decline() {
        let mut r = Record::new();
        r.append(Step::declared(
            Activity::Dispatched,
            Outcome::Observe,
            Phase::Construction,
        ))
        .unwrap();
        r.append(Step::declared(
            Activity::Dispatched,
            Outcome::Decline,
            Phase::Construction,
        ))
        .unwrap();
        assert_ne!(r.steps()[0].outcome, r.steps()[1].outcome);
    }

    // --- coherence ---

    #[test]
    fn a_loop_that_closes_within_the_floor_is_unresolvable_not_coherent() {
        // ⭐ The distinction the note insists on. 20.0 vs 20.3 with ±2% legs: the
        // discrepancy is real but below β, so no claim can be made either way.
        let c = Cycle::new(
            "harvest",
            vec![
                Leg::new("area_x_yield", t(20.0, Source::Asserted, Some(0.02))),
                Leg::new("weighbridge", t(20.3, Source::Weighbridge, Some(0.02))),
            ],
        );
        let r = check_cycle(&c);
        assert_eq!(r.closure, Closure::SubFloor);
        assert!(!r.closure.alerts(), "β is the no-alert band");
        assert!(r.discrepancy < r.beta);
    }

    #[test]
    fn a_loop_that_does_not_close_across_disjoint_sources_is_incoherent() {
        let c = Cycle::new(
            "harvest",
            vec![
                Leg::new("declared", t(40.0, Source::Asserted, Some(0.02))),
                Leg::new("weighbridge", t(18.0, Source::Weighbridge, Some(0.02))),
            ],
        );
        let r = check_cycle(&c);
        assert_eq!(r.closure, Closure::Incoherent);
        assert!(r.closure.alerts());
        assert_eq!(r.disjoint_sources, 2);
    }

    #[test]
    fn disagreement_among_correlated_sources_is_contested_not_incoherent() {
        // ⚠️ Three claims from the same farmer that disagree. Something is wrong, but
        // it is not evidence about the world — correlated sources do not compose.
        let c = Cycle::new(
            "harvest",
            vec![
                Leg::new("sms_march", t(40.0, Source::Asserted, Some(0.02))),
                Leg::new("sms_april", t(18.0, Source::Asserted, Some(0.02))),
                Leg::new("sms_may", t(31.0, Source::Asserted, Some(0.02))),
            ],
        );
        let r = check_cycle(&c);
        assert_eq!(r.closure, Closure::Contested);
        assert_eq!(r.disjoint_sources, 1, "three steps, one source");
        assert!(r.confidence.is_wholly_asserted());
    }

    #[test]
    fn re_inspecting_the_same_way_twice_earns_nothing() {
        // The anti-monoculture result, as a counting property.
        let same = Cycle::new(
            "x",
            vec![
                Leg::new("a", t(10.0, Source::Asserted, Some(0.01))),
                Leg::new("b", t(10.0, Source::Asserted, Some(0.01))),
                Leg::new("c", t(10.0, Source::Asserted, Some(0.01))),
            ],
        );
        let mixed = Cycle::new(
            "y",
            vec![
                Leg::new("a", t(10.0, Source::Asserted, Some(0.01))),
                Leg::new("b", t(10.0, Source::Weighbridge, Some(0.01))),
            ],
        );
        assert_eq!(same.disjoint_source_count(), 1);
        assert_eq!(mixed.disjoint_source_count(), 2);
    }

    #[test]
    fn unknown_precision_widens_beta_rather_than_tightening_it() {
        // If unknown precision were treated as perfect, this loop would alert. It must
        // not: the failure direction has to be toward silence, not toward noise.
        let c = Cycle::new(
            "harvest",
            vec![
                Leg::new("declared", t(20.0, Source::Asserted, None)),
                Leg::new("estimate", t(23.0, Source::ThirdParty, None)),
            ],
        );
        let r = check_cycle(&c);
        assert!(
            r.beta > 3.0,
            "β should exceed the 3t discrepancy, got {}",
            r.beta
        );
        assert_eq!(r.closure, Closure::SubFloor);
    }

    #[test]
    fn the_band_is_never_narrower_than_the_floor() {
        // ⭐ Note 16 §2.4: forward contracts are banded, and the band cannot claim
        // precision below the measurement floor. Two legs agreeing exactly still yields
        // a band of width β, not a point.
        let c = Cycle::new(
            "forward",
            vec![
                Leg::new("a", t(20.0, Source::Weighbridge, Some(0.05))),
                Leg::new("b", t(20.0, Source::Instrument, Some(0.05))),
            ],
        );
        let r = check_cycle(&c);
        assert_eq!(r.discrepancy, 0.0);
        assert!(r.band_width() > 0.0, "an exact agreement is still a band");
        assert!((r.band_width() - r.beta).abs() < 1e-9);
    }

    #[test]
    fn the_band_narrows_as_evidence_improves() {
        // The visible product: same quantity, better instruments, tighter band.
        let early = Cycle::new(
            "yield",
            vec![
                Leg::new("a", t(20.0, Source::Asserted, None)),
                Leg::new("b", t(21.0, Source::Asserted, None)),
            ],
        );
        let late = Cycle::new(
            "yield",
            vec![
                Leg::new("a", t(20.0, Source::Weighbridge, Some(0.01))),
                Leg::new("b", t(20.1, Source::CommercialRecord, Some(0.01))),
            ],
        );
        assert!(check_cycle(&late).band_width() < check_cycle(&early).band_width());
    }

    #[test]
    fn an_alert_reports_the_confidence_of_what_raised_it() {
        // So a reader can tell an alert on weighbridge data from an alert on guesses.
        let c = Cycle::new(
            "harvest",
            vec![
                Leg::new("declared", t(40.0, Source::Asserted, None)),
                Leg::new("weighbridge", t(18.0, Source::Weighbridge, Some(0.02))),
            ],
        );
        let r = check_cycle(&c);
        assert!(r.closure.alerts());
        assert_eq!(r.confidence.floor, 0.0, "the asserted leg is the floor");
        assert_eq!(r.confidence.asserted_fields, vec!["declared"]);
    }

    #[test]
    fn a_cycle_with_fewer_than_two_legs_closes_nothing() {
        let one = Cycle::new("x", vec![Leg::new("a", t(20.0, Source::Asserted, None))]);
        let r = check_cycle(&one);
        assert_eq!(r.closure, Closure::Degenerate);
        assert!(!r.closure.alerts());
        assert_eq!(r.band, (20.0, 20.0));

        let none = Cycle::new("x", vec![]);
        assert_eq!(check_cycle(&none).closure, Closure::Degenerate);
    }

    #[test]
    fn the_check_is_deterministic() {
        let c = Cycle::new(
            "harvest",
            vec![
                Leg::new("a", t(40.0, Source::Asserted, Some(0.03))),
                Leg::new("b", t(18.0, Source::Weighbridge, Some(0.02))),
            ],
        );
        let first = check_cycle(&c);
        for _ in 0..10 {
            assert_eq!(check_cycle(&c), first);
        }
    }

    #[test]
    fn the_wire_shape_of_a_step_is_stable() {
        let s = Step::observed(
            Activity::Harvested,
            Outcome::Commit,
            Phase::Commitment,
            Source::Weighbridge,
        );
        let json = serde_json::to_string(&s).unwrap();
        assert_eq!(
            json,
            r#"{"tick":0,"activity":"harvested","outcome":"commit","phase":"commitment","source":"weighbridge"}"#
        );
        assert_eq!(serde_json::from_str::<Step>(&json).unwrap(), s);
    }
}
